#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_index.py — 生成 .index/manifest.md + manifest/<cat>.md + topics.md

派生型文件，每次全量重建。
"""

import sys
import re
from pathlib import Path
from datetime import datetime
from collections import defaultdict

sys.path.insert(0, str(Path(__file__).parent))
from common import (
    VAULT_ROOT, scan_notes, rel_path, meta_mirror,
    scan_office_docs, OFFICE_EXTRACTS_DIR,
)

INDEX_DIR = VAULT_ROOT / '.index'
MANIFEST_DIR = INDEX_DIR / 'manifest'

AUTO_NOTICE = "<!-- AUTO-GENERATED by .meta/scripts/build_index.py · 下次维护会覆盖本文件 -->"


def extract_title(content: str) -> str:
    for line in content.splitlines()[:30]:
        m = re.match(r'^#\s+(.+)', line.strip())
        if m:
            return m.group(1).strip()
    return ""


def extract_date(filename: str) -> str:
    m = re.match(r'^(\d{4})(\d{2})(\d{2})', Path(filename).name)
    if m:
        return f"{m.group(1)}-{m.group(2)}-{m.group(3)}"
    return "—"


def get_category(rel: str) -> str:
    """取路径第一段为分类（假设扁平一级分类；深层嵌套仓库请自行调整）。"""
    parts = rel.split('/')
    if len(parts) == 1:
        return "(收件箱)"
    return parts[0]


def collect_entries():
    entries = []
    for md in scan_notes():
        rel = rel_path(md)
        try:
            content = md.read_text(encoding='utf-8')
        except:
            continue
        entries.append({
            'path': rel,
            'filename': md.name,
            'category': get_category(rel),
            'date': extract_date(md.name),
            'title': extract_title(content),
            'lines': len(content.splitlines()),
            'chars': len(content),
        })

    # office 文档：按源文件登记；摘要/行数取自 extract sidecar（若已提取）
    for doc in scan_office_docs():
        rel = rel_path(doc)
        extract = OFFICE_EXTRACTS_DIR / (rel + '.md')
        lines = chars = 0
        if extract.exists():
            try:
                text = extract.read_text(encoding='utf-8')
                lines, chars = len(text.splitlines()), len(text)
            except Exception:
                pass
        entries.append({
            'path': rel,
            'filename': doc.name,
            'category': get_category(rel),
            'date': extract_date(doc.name),
            'title': doc.stem,
            'lines': lines,
            'chars': chars,
            'doc_type': 'office',
            'summary_key': rel_path(extract) if extract.exists() else '',
        })
    return entries


def load_summary(rel: str) -> str:
    p = meta_mirror(VAULT_ROOT / rel, 'summaries')
    if not p.exists():
        return ""
    try:
        text = p.read_text(encoding='utf-8')
    except:
        return ""
    parts = text.split('---', 2)
    if len(parts) >= 3:
        return parts[2].strip()
    return text.strip()


def load_tags(rel: str) -> list:
    p = meta_mirror(VAULT_ROOT / rel, 'tags')
    if not p.exists():
        return []
    tags = []
    try:
        for line in p.read_text(encoding='utf-8').splitlines():
            m = re.match(r'^-\s+#(\S+)', line)
            if m:
                tags.append(m.group(1))
    except:
        pass
    return list(set(tags))


def build_manifest_top(entries) -> str:
    by_cat = defaultdict(list)
    for e in entries:
        by_cat[e['category']].append(e)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# 知识库总索引 Manifest",
        f"> Last updated: {now} | Total: {len(entries)} 篇笔记",
        AUTO_NOTICE,
        "",
        "## 分类一览",
        "",
        "| 分类 | 文件数 | 详细清单 |",
        "|------|-------:|---------|",
    ]
    for cat in sorted(by_cat.keys()):
        count = len(by_cat[cat])
        if cat == "(收件箱)":
            link = "见下"
        else:
            safe = cat.replace('/', '_')
            link = f"[{cat}](./manifest/{safe}.md)"
        lines.append(f"| {cat} | {count} | {link} |")
    lines.append("")

    inbox = by_cat.get("(收件箱)", [])
    if inbox:
        lines += [
            "## 收件箱（根目录待归类）",
            "",
            "| 日期 | 文件 | 行数 |",
            "|------|------|-----:|",
        ]
        for e in sorted(inbox, key=lambda x: x['date'], reverse=True):
            lines.append(f"| {e['date']} | `{e['filename']}` | {e['lines']} |")
        lines.append("")

    return "\n".join(lines)


def build_manifest_category(cat: str, entries) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# {cat} — 详细清单",
        f"> Last updated: {now} | {len(entries)} 篇",
        AUTO_NOTICE,
        "",
        "| 日期 | 文件 | 行数 | 摘要 |",
        "|------|------|-----:|------|",
    ]
    for e in sorted(entries, key=lambda x: (x['date'], x['filename']), reverse=True):
        if e.get('doc_type') == 'office':
            s = (load_summary(e['summary_key']).replace('\n', ' ')[:100]
                 if e.get('summary_key') else '（未提取）')
            name = f"📎 {e['filename']}"
        else:
            s = load_summary(e['path']).replace('\n', ' ')[:100]
            name = e['filename']
        s = s or '—'
        lines.append(f"| {e['date']} | `{name}` | {e['lines']} | {s} |")
    lines.append("")
    return "\n".join(lines)


def build_topics(entries) -> str:
    tag_files = defaultdict(list)
    for e in entries:
        for tag in load_tags(e.get('summary_key') or e['path']):
            tag_files[tag].append(e)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "# 主题索引 Topics",
        f"> Last updated: {now} | Tags: {len(tag_files)}",
        AUTO_NOTICE,
        "",
        "## 使用说明",
        "- 按 tag 聚合笔记。Tag 来源：用户内联 `#xxx` + Agent 建议（存 `.meta/tags/`）",
        "- 一篇笔记可能出现在多个 tag 下",
        "",
    ]

    for tag, files in sorted(tag_files.items(), key=lambda x: -len(x[1])):
        lines.append(f"## #{tag} · {len(files)} 篇")
        lines.append("")
        for e in sorted(files, key=lambda x: x['date'], reverse=True):
            lines.append(f"- `{e['path']}` — {e['title'] or e['filename']}")
        lines.append("")

    return "\n".join(lines)


def main():
    INDEX_DIR.mkdir(exist_ok=True)
    MANIFEST_DIR.mkdir(exist_ok=True)

    entries = collect_entries()
    print(f"  处理 {len(entries)} 篇笔记")

    # 顶层 manifest
    (INDEX_DIR / 'manifest.md').write_text(build_manifest_top(entries), encoding='utf-8')

    # 各分类 manifest
    for f in MANIFEST_DIR.glob('*.md'):
        f.unlink()

    by_cat = defaultdict(list)
    for e in entries:
        by_cat[e['category']].append(e)

    for cat, items in by_cat.items():
        if cat == "(收件箱)":
            continue
        safe = cat.replace('/', '_')
        (MANIFEST_DIR / f"{safe}.md").write_text(
            build_manifest_category(cat, items), encoding='utf-8'
        )

    # topics
    (INDEX_DIR / 'topics.md').write_text(build_topics(entries), encoding='utf-8')
    print(f"  ✓ 完成 manifest.md + manifest/ ({len(by_cat)} 分类) + topics.md")
    return 0


if __name__ == "__main__":
    # --- host guard ---
    from pathlib import Path
    import sys
    sys.path.insert(0, str(Path(__file__).parent))
    from common import is_primary_host
    if not is_primary_host():
        print("FATAL: this script must run on PRIMARY_HOST", file=sys.stderr)
        sys.exit(1)
    # --- /host guard ---
    sys.exit(main())
